### ISSUE TITLE
How run tests parallel?

### ISSUE THREAD

**Issue by endeffects** [goeaway/SeleniumFluentAPI#2]
Hi, i tried your fluent framework from the Locator branch today and i really like it.
I'd like to know how to run the browser tests in parallel with xunit.

I cannot figure out how archive this. All my other tests are getting executed in parallel,
but as soon as i'm using the selenium script tests only one test gets executed at time.

Any ideas?

**Comment by goeaway** [comment]
Apologies, I haven't checked this repo for a while and missed any notification. Did you manage to get your problem resolved?

**Comment by endeffects** [comment]
Thanks for your reply, i stopped using the library and gone back to write my tests low level. So no, i did not got this to work.
